Repository microsoftwo/be14-3rd-microsoftwo-clother, pull requests merged in 2025-04, with the labels that each got.

#2 [feat] Header, Footer 컴포넌트 및 마이페이지 구현
  .gitignore
  src/components/Footer.vue
  src/components/Header.vue
  src/components/PostGrid.vue
  src/components/Profile.vue
  src/views/MyPage.vue
Labels: 🚘 feature

#3 [fix] Header 네비게이션 바 수정
  src/components/Footer.vue
  src/components/Header.vue
  src/components/PostGrid.vue
  src/router/index.js
  src/views/MyPage.vue
Labels: 🐛 fix

#6 [feat] Header 컴포넌트에 드롭다운 형태의 카테고리 추가
  src/App.vue
  src/components/Header.vue
  src/components/Profile.vue
  src/components/ProfileEditModal.vue
  src/constants/images.js
  src/router/index.js
  src/views/MyPage.vue
  src/views/ProfileEdit.vue
Labels: 🚘 feature

#5 [feat] styleshare 게시글 등록 화면 UI 구현
  src/components/style-share/StyleShareForm.vue
  src/router/index.js
  src/views/StyleShareCreate.vue
Labels: 🚘 feature

#8 [fix] Header 라우팅 오류 해결
  src/components/Header.vue
Labels: 🐛 fix

#10 [feat] Header 디자인 수정
  src/components/Header.vue
Labels: 🚘 feature, 🏠 refactor

#13 [hotfix] vue-router 설정 추가
  src/router/index.js
Labels: 🚨 hotfix

#16 [feat] Header 카테고리 클릭 시 토글 닫히게 수정
  src/components/Header.vue
Labels: 🚘 feature

#18 [feat] MainPage 구현
  package-lock.json
  package.json
  src/components/Header.vue
  src/components/ImageCard.vue
  src/components/LikesGrid.vue
  src/components/NewestGrid.vue
  src/router/index.js
  src/views/MainPage.vue
  vite.config.js
Labels: 🚘 feature

#20 [feat] 상단 카테고리별 필터 기능 구현
  src/components/CategoryGrid.vue
  src/components/CategoryLikesGrid.vue
  src/components/CategoryNewestGrid.vue
  src/constants/categoryMap.js
  src/router/index.js
Labels: 🚘 feature

#14 [feat] 로그인 컴포넌트 추가
  src/views/LoginForm.vue
Labels: 🚘 feature

#11 [feat] Mypage 나의 활동 기록 구현
  src/App.vue
  src/components/Header.vue
  src/constants/images.js
  src/icons/likes_10.jpg
  src/icons/likes_11.jpg
  src/icons/likes_2.jpg
  src/icons/likes_3.jpg
  src/icons/likes_4.jpg
  src/icons/likes_5.jpg
  src/icons/likes_6.jpg
  src/icons/likes_7.jpg
  src/icons/likes_8.jpg
  src/icons/likes_9.jpg
  src/icons/profile_1.jpg
  src/icons/profile_2.jpg
  src/icons/profile_3.png
  src/icons/profile_4.png
  src/icons/profile_5.jpg
  src/icons/profile_6.jpg
  src/router/index.js
  src/views/MyActivity.vue
  src/views/MyPage.vue
  vite.config.js
Labels: 🚘 feature

#21 [feat] Footer 에 개인정보처리방침, 이용약관 페이지 추가
  src/App.vue
  src/components/Footer.vue
  src/components/Profile.vue
  src/router/index.js
  src/views/PrivacyPolicy.vue
  src/views/Terms.vue
Labels: 🚘 feature

#24 [feat] 회원가입 UI 구현
  src/components/SignupForm.vue
  src/components/StyleShareForm.vue
  src/router/index.js
  src/views/ProfileEdit.vue
  src/views/StyleShareCreate.vue
Labels: 🚘 feature

#26 [fix] index.js의 누락된 코드 복구, 경로 지정
  src/router/index.js
  src/views/SignupForm.vue
Labels: 🐛 fix, 🚨 hotfix

#36 [feat] MainPage 배경색 지정, 버튼 색 변경
  src/App.vue
  src/components/Header.vue
  src/views/MainPage.vue
Labels: 🚘 feature

#38 [feat] CLOTHER 로고 누를 시 메인페이지 가도록 수정
  src/router/index.js
  src/views/MainPage.vue
Labels: 🚘 feature

#46 [feat] 웹페이지 로고, 제목 수정
  index.html
  public/logo.png
Labels: 🚘 feature

#59 [feat] 랜딩페이지 생성
  package-lock.json
  package.json
  public/images/style1.jpg
  public/images/style2.jpg
  public/images/style3.jpg
  public/images/style4.jpg
  src/assets/image/IMG_4978.JPG
  src/assets/image/IMG_5519.JPG
  src/assets/image/IMG_6523.JPG
  src/assets/image/IMG_6739.JPG
  src/assets/image/IMG_9443.JPG
  src/assets/image/main.png
  src/assets/image/moka.png
  src/assets/image/mypage.png
  src/assets/image/newest.png
  src/assets/image/sc.png
  src/components/GsapScroll.vue
  src/components/Header.vue
  src/router/index.js
  src/styles/gsap-scroll.css
Labels: 🚘 feature

#61 [feat] 랜딩페이지에서 로그인창 이동시 버그 수정
  src/components/GsapScroll.vue
Labels: 🚘 feature

#64 [fix] index.js 경로 수정
  src/router/index.js
  vite.config.js
Labels: 🐛 fix, 🏠 refactor
